### ISSUE TITLE
Rendering Glider Bug [1.19.2]

### ISSUE THREAD

**Issue by Exokyhh** [Jeryn99/MC-Gliders#62]
When this mod is installed with Oculus (the forge version of Iris, used for shaders: https://www.curseforge.com/minecraft/mc-mods/oculus), while gliding in first person there will be a small rendering bug next to the cursor, where a small glider is seen moving strangely in random directions. I tested this mod with Oculus only, and the issue still persists, so it's an incompatibility between these 2 mods.

Tested in 1.19.2 with:
- Forge - 43.3.0
- vc_gliders-forge-1.1.4.jar _(i see that the last 2 version of 1.19 have the same name, but it's the most recent one)_
- oculus-mc1.19.2-1.6.9.jar (with ComplementaryReimagined_r5.1.1 shaders)

![glider2](https://github.com/Jeryn99/MC-Gliders/assets/90096585/a71ec7b4-76dc-48b6-9702-b377f8f6f9ce)

https://github.com/Jeryn99/MC-Gliders/assets/90096585/af944e2b-f57a-48b8-b9ec-28b240c45bb2

https://github.com/Jeryn99/MC-Gliders/assets/90096585/8986c10e-5a95-4dd5-9d5a-51132c0c9026

**Comment by PreciseModpacker** [comment]
Hi! This problem was solved for me when I use AzureLib for Forge 1.19.2 insteat of Geckolib https://www.curseforge.com/minecraft/mc-mods/azurelib

I hope it helps!

**Comment by Jeryn99** [comment]
This issue is invalid due to the use of performance enhancing mods that rewrite parts of the rendering engine.

**Comment by Exokyhh** [comment]
I only had Embeddium and Oculus... which one are you talking about?

**Comment by Jeryn99** [comment]
Both
